module.exports = {
  leetcode: [
    'leetcode/index',
    'leetcode/a1',
    'leetcode/a15',
    'leetcode/a20',
    'leetcode/a55',
    'leetcode/a94',
  ],
  sort: [
    'sort/index',
    'sort/a1',
    'sort/a2',
    'sort/a3',
    'sort/a4',
    'sort/a5',
    'sort/a6',
    'sort/a7',
    'sort/a8',
    'sort/a9',
  ],
  datastructure: [
    'data-structure/index',
    'data-structure/a0',
    'data-structure/a1',
    'data-structure/a2',
    'data-structure/a3',
    'data-structure/a4',
    'data-structure/a5',
    'data-structure/a6',
    'data-structure/a7',
    'data-structure/a71',
  ],
  algorithm: ['algorithom/index'],
  designpattern: [
    'design-pattern/index',
    'design-pattern/a1',
    'design-pattern/a2',
    'design-pattern/a3',
    'design-pattern/a4',
    'design-pattern/a5',
    'design-pattern/a6',
    'design-pattern/a7',
    'design-pattern/a8',
    'design-pattern/a9',
    'design-pattern/a90',
    'design-pattern/a91',
    'design-pattern/a92',
    'design-pattern/a93',
    'design-pattern/a94',
  ],
  js: [
    'write-js/index',
    'write-js/a1',
    'write-js/a2',
    'write-js/a3',
    'write-js/a31',
    'write-js/a32',
    'write-js/a33',
    'write-js/a34',
    'write-js/a35',
    'write-js/a36',
  ],
  interview: ['interview/index'],
  react: [
    'react/index',
    'react/a1',
    'react/a11',
    'react/a12',
    'react/a13',
    'react/a14',
    'react/a15',
    'react/a16',
    'react/a17',
    'react/a18',
    'react/a19',
    'react/a20',
    'react/a21',
    'react/a22',
    'react/a23',
    'react/a24',
  ],
  reactRedux: [
    'react-redux/index',
    'react-redux/a1',
    'react-redux/a2',
    'react-redux/a3',
    'react-redux/a4',
  ],
  redux: [
    'write-redux/index',
    'write-redux/a1',
    'write-redux/a2',
    'write-redux/a3',
  ],
};
